# Generated by Django 5.1.5 on 2025-07-01 14:46

import apps.vendas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, help_text='Valor total da venda em Kwanza', max_digits=12, verbose_name='Valor da Venda (Kz)')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Entrada (Kz)')),
                ('valor_financiado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Financiado (Kz)')),
                ('tipo_pagamento', models.CharField(choices=[('a_vista', 'À Vista'), ('financiado', 'Financiado'), ('misto', 'Misto')], max_length=20, verbose_name='Tipo de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, help_text='Dinheiro, Transferência, Cartão, etc.', max_length=100, verbose_name='Forma de Pagamento')),
                ('banco_financiamento', models.CharField(blank=True, max_length=100, verbose_name='Banco de Financiamento')),
                ('numero_parcelas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Parcelas')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.carro', verbose_name='Carro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario', verbose_name='Funcionário Responsável')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(help_text='Contrato, Nota Fiscal, etc.', max_length=100, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(help_text='Arquivo do documento', upload_to=apps.vendas.models.documento_venda_path, verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Documento de Venda',
                'verbose_name_plural': 'Documentos de Vendas',
                'db_table': 'documento_venda',
                'ordering': ['-data_upload'],
            },
        ),
    ]
