# Generated by Django 5.1.5 on 2025-07-06 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.venda', verbose_name='Venda Relacionada'),
        ),
        migrations.AddField(
            model_name='carro',
            name='opcionais',
            field=models.ManyToManyField(blank=True, related_name='carros', to='veiculos.opcional', verbose_name='Opcionais'),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('marca', 'nome')},
        ),
    ]
