# Generated by Django 5.1.5 on 2025-07-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Chave única da configuração', max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(blank=True, help_text='Valor da configuração', null=True, verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da configuração', null=True, verbose_name='Descrição')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'db_table': 'configuracoes',
                'ordering': ['chave'],
            },
        ),
    ]
