# Generated by Django 5.1.5 on 2025-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim_prevista', models.DateField(verbose_name='Data de Fim Prevista')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='Data de Fim Real')),
                ('valor_diario', models.DecimalField(decimal_places=2, help_text='Valor do aluguel por dia em Kwanza', max_digits=8, verbose_name='Valor Diário (Kz)')),
                ('valor_total_previsto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Previsto (Kz)')),
                ('valor_total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total Final (Kz)')),
                ('quilometragem_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem Inicial')),
                ('quilometragem_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem Final')),
                ('deposito_caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depósito Caução (Kz)')),
                ('observacoes_entrega', models.TextField(blank=True, verbose_name='Observações de Entrega')),
                ('observacoes_devolucao', models.TextField(blank=True, verbose_name='Observações de Devolução')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('atrasado', 'Atrasado')], default='ativo', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'verbose_name_plural': 'Aluguéis',
                'db_table': 'aluguel',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do pagamento em Kwanza', max_digits=10, verbose_name='Valor (Kz)')),
                ('tipo_pagamento', models.CharField(blank=True, help_text='Diário, Semanal, Total, etc.', max_length=50, verbose_name='Tipo de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, help_text='Dinheiro, Transferência, Cartão, etc.', max_length=100, verbose_name='Forma de Pagamento')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Pagamento de Aluguel',
                'verbose_name_plural': 'Pagamentos de Aluguéis',
                'db_table': 'pagamento_aluguel',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
