# Generated by Django 5.1.5 on 2025-07-06 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alugueis', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.carro', verbose_name='Carro'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.funcionario', verbose_name='Funcionário Responsável'),
        ),
        migrations.AddField(
            model_name='pagamentoaluguel',
            name='aluguel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alugueis.aluguel', verbose_name='Aluguel'),
        ),
    ]
